CREATE DATABASE EMPRESA_TARDE;
GO

USE EMPRESA_TARDE;
GO

CREATE TABLE PESSOA (
idPessoa SMALLINT PRIMARY KEY IDENTITY (1,1),
nomePessoa VARCHAR(20)
);
GO

ALTER TABLE PESSOA
DROP COLUMN nomePessoa

ALTER TABLE PESSOA
ADD nomePessoa VARCHAR(20) NOT NULL

CREATE TABLE TELEFONE(

idTelefone SMALLINT PRIMARY KEY IDENTITY (1,1),
idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(idPessoa),
numeroTelefone CHAR(20) NOT NULL

);
GO