CREATE DATABASE LOCADORA;
GO

USE LOCADORA;
GO

CREATE TABLE EMPRESA(
 idEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
 nomeEmpresa VARCHAR(30) NOT NULL
);
GO

CREATE TABLE MARCA(
 idMarca SMALLINT PRIMARY KEY IDENTITY(1,1),
 nomeMarca VARCHAR(20) NOT NULL
);
GO

CREATE TABLE MODELO(
 idModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
 idMarca SMALLINT FOREIGN KEY REFERENCES MARCA(idMarca),
 nomeModelo VARCHAR(25) NOT NULL
);
GO

CREATE TABLE VEICULO(
 idVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
 idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
 idEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
 placa VARCHAR(10) NOT NULL
);
GO

CREATE TABLE CLIENTE(
 idCLiente SMALLINT PRIMARY KEY IDENTITY(1,1),
 nomeCliente VARCHAR(25) NOT NULL,
 cpfCliente VARCHAR(13) NOT NULL
);
GO

CREATE TABLE ALUGUEL(
 idAluguel SMALLINT PRIMARY KEY IDENTITY(1,1),
 idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
 idCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE(idCliente),
 dataInicio DATETIME NOT NULL,
 dataFim DATETIME NOT NULL
);
GO

INSERT EMPRESA (nomeEmpresa)
VALUES ('unidas'), ('movida')

INSERT MARCA (nomeMarca)
VALUES ('chevrolet'), ('fiat')

INSERT MODELO (idMarca,nomeModelo)
VALUES (1,'onix'),(2,'uno')

INSERT VEICULO (idModelo,idEmpresa,placa)
VALUES (1,1,'CNH1234'),(2,2,'FGV5665')

INSERT CLIENTE (nomeCliente,cpfCliente)
VALUES ('lucas','11111111111'),('saulo','22222222222')

INSERT ALUGUEL(idVeiculo,idCliente, dataInicio, dataFim)
VALUES (3,1, '9/08/2021', '15/08/2021'),(4,2, '15/08/2021', '24/08/2021')

SELECT * FROM EMPRESA
SELECT * FROM MARCA
SELECT * FROM MODELO
SELECT * FROM VEICULO
SELECT * FROM CLIENTE
SELECT * FROM ALUGUEL

SELECT CLIENTE.nomeCliente AS CLIENTE,dataInicio AS 'DATA DE INÍCIO', dataFim AS 'DATA DE FIM', MODELO.nomeModelo AS MODELO FROM ALUGUEL
INNER JOIN CLIENTE
ON ALUGUEL.idCliente = Cliente.idCLiente
INNER JOIN VEICULO
ON ALUGUEL.idVeiculo = VEICULO.idVeiculo
INNER JOIN MODELO
ON MODELO.idModelo = VEICULO.idModelo

SELECT CLIENTE.nomeCliente AS CLIENTE,dataInicio AS 'DATA DE INÍCIO', dataFim AS 'DATA DE FIM', MODELO.nomeModelo AS MODELO FROM ALUGUEL
INNER JOIN CLIENTE
ON ALUGUEL.idCliente = Cliente.idCLiente
INNER JOIN VEICULO
ON ALUGUEL.idVeiculo = VEICULO.idVeiculo
INNER JOIN MODELO
ON MODELO.idModelo = VEICULO.idModelo
WHERE CLIENTE.nomeCliente = 'saulo';
 


