USE CATALOGO_TARDE
GO
SELECT * FROM FILME
SELECT * FROM GENERO_FILME

DELETE FROM FILME
WHERE idFilme in (13,14,15,16,17,18)


-- SELECIONAR TODOS OS FILMES E OS GÊNEROS RELACIONADOS
-- LEFT JOIN
SELECT idFilme, tituloFilme, nomeGenero FROM FILME
LEFT JOIN GENERO_FILME
ON FILME.idGenero = GENERO_FILME.idGenero;


-- SELECIONAR SOMENTE OS FILMES QUE POSSUEM RELAÇÃO COM GÊNERO 
-- E OS TODOS OS OUTROS GÊNEROS 
-- RIGHT JOIN
SELECT idFilme, tituloFilme, nomeGenero
FROM FILME
RIGHT JOIN GENERO_FILME
ON FILME.idGenero = GENERO_FILME.idGenero;


-- SELECIONAR SOMENTE OS FILMES QUE POSSUEM RELAÇÃO COM GÊNERO
-- INNER JOIN
SELECT idFilme, tituloFilme, nomeGenero
FROM FILME
INNER JOIN GENERO_FILME
ON FILME.idGenero = GENERO_FILME.idGenero;


-- SELECIONAR TODOS OS FILMES E TODOS OS GÊNEROS
-- MESMO QUE NÃO HAJA CORRESPONDÊNCIA
-- FULL OUTER JOIN
SELECT idFilme, tituloFilme, nomeGenero
FROM FILME
FULL OUTER JOIN GENERO_FILME
ON FILME.idGenero = GENERO_FILME.idGenero;