USE CATALOGO_TARDE;
GO

INSERT INTO GENERO_FILME(nomeGenero)
VALUES ('AÇÃO'), ('ROMANCE');
GO

SELECT * FROM GENERO_FILME

DELETE FROM GENERO_FILME
WHERE idGenero = 2;

INSERT INTO FILME (tituloFilme,idGenero)
VALUES ('RAMBO',1), ('VINGADORES',1),
('GHOST',2), ('DIARIO DE UMA PAIXAO',2)

SELECT * FROM FILME

UPDATE FILME SET tituloFilme = 'Rambo 2'
WHERE idFilme = 1

DELETE FROM FILME
WHERE idFilme in(2,3)