CREATE DATABASE EMPRESA;
GO

USE EMPRESA;
GO

CREATE TABLE PESSOA (
idPessoa SMALLINT PRIMARY KEY IDENTITY (1,1),
nomePessoa VARCHAR(20) NOT NULL
);
GO

CREATE TABLE TELEFONE(
idTelefone SMALLINT PRIMARY KEY IDENTITY (1,1),
idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(idPessoa),
numeroTelefone CHAR(20) NOT NULL
);
GO

CREATE TABLE EMAIL(
idEmail INT PRIMARY KEY IDENTITY (1,1),
idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA (idPessoa),
end_email VARCHAR (256) NOT NULL UNIQUE
);
GO

--DROP TABLE EMAIL

CREATE TABLE CNH(
idCNH SMALLINT PRIMARY KEY IDENTITY(1,1),
idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA (idPessoa),
descricao CHAR(11) NOT NULL UNIQUE
);
GO

INSERT PESSOA (nomePessoa)
VALUES ('SAULO'),('LUCAS')

INSERT TELEFONE (idPessoa, numeroTelefone)
VALUES (1, '222'), (2, '111') 

INSERT EMAIL (idPessoa, end_email)
VALUES (1,'saulo@email.com'),(2,'lucas@email.com')

INSERT CNH(idPessoa,descricao)
VALUES (1,'1234'),(2,'5678')

SELECT * FROM PESSOA
SELECT * FROM TELEFONE
SELECT * FROM EMAIL
SELECT * FROM CNH

SELECT  nomePessoa, telefone.numeroTelefone, email.end_email, cnh.descricao as cnh FROM PESSOA
INNER JOIN TELEFONE
ON PESSOA.idPessoa = TELEFONE.idPessoa
INNER JOIN EMAIL
ON PESSOA.idPessoa = EMAIL.idPessoa
INNER JOIN CNH
ON PESSOA.idPessoa = CNH.idPessoa;
GO
--ORDER BY nomePessoa DESC