CREATE DATABASE EMPRESA_TARDE;
GO

USE EMPRESA_TARDE;
GO

CREATE TABLE PESSOA (
idPessoa SMALLINT PRIMARY KEY IDENTITY (1,1),
nomePessoa VARCHAR(20) NOT NULL
);
GO

CREATE TABLE TELEFONE(
idTelefone SMALLINT PRIMARY KEY IDENTITY (1,1),
idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(idPessoa),
numeroTelefone CHAR(20) NOT NULL
);
GO

CREATE TABLE EMAIL(
idEmail INT PRIMARY KEY IDENTITY (1,1),
idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA (idPessoa),
descricao VARCHAR (256) NOT NULL UNIQUE
);
GO

--DROP TABLE EMAIL

CREATE TABLE CNH(
idCNH SMALLINT PRIMARY KEY IDENTITY(1,1),
idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA (idPessoa),
descricao CHAR(11) NOT NULL UNIQUE
);
GO

INSERT PESSOA (nomePessoa)
VALUES ('SAULO'),('LUCAS')

SELECT * FROM PESSOA

INSERT TELEFONE (idPessoa, numeroTelefone)
VALUES (1, '1'), (2, '111')

SELECT * FROM TELEFONE

INSERT EMAIL (idPessoa, descricao)
VALUES (1,'saulo@email.com'),(2,'lucas@email.com')

SELECT * FROM EMAIL

INSERT CNH(idPessoa,descricao)
VALUES (1,'1234'),(2,'5678')

SELECT * FROM CNH